language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run travis-deploy
deploy:
  provider: surge
  skip_cleanup: true
  domain: vimulator2.surge.sh
  project: ./build/