language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm build
deploy:
  provider: surge
  skip_cleanup: true
  domain: vimulator2.surge.sh
  project: ./build/