export const FETCH_USERDATA_START = 'FETCH_USERDATA_START'
export const FETCH_USERDATA_SUCCESS = 'FETCH_USERDATA_SUCCESS'
export const FETCH_USERDATA_FAIL = 'FETCH_USERDATA_FAIL'
export const UPDATE_LESSON = 'UPDATE_LESSON'